name: Spelling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spelling check
        uses: crate-ci/typos@master
